from search_address_parser.core.definition import Definition, MatchPosition

REGION_DEFINITIONS = [
    Definition(value="Область", abbreviations=['Обл'], match_pos=MatchPosition.LEFT),
    Definition(value="Автономный округ", abbreviations=['АО'],  match_pos=MatchPosition.RIGHT),
    Definition(value="Автономная область", abbreviations=['авт.обл', 'авт обл'], match_pos=MatchPosition.LEFT),
    Definition(value="Край", abbreviations=[], match_pos=MatchPosition.LEFT),
    Definition(value="Республика", abbreviations=['респ'], match_pos=MatchPosition.RIGHT)
]

CITY_DEFINITIONS = [
    Definition(value="город", abbreviations=['г'], match_pos=MatchPosition.RIGHT),
    Definition(value="посёлок городского типа", abbreviations=['п.г.т'], match_pos=MatchPosition.RIGHT),
    Definition(value="посёлок при станции", abbreviations=['п-ст', 'п.ст'],  match_pos=MatchPosition.RIGHT),
    Definition(value="район", abbreviations=['п-ст', 'р-н']),
    Definition(value="рабочий посёлок", abbreviations=['р.п'], match_pos=MatchPosition.RIGHT),
    Definition(value="курортный посёлок", abbreviations=['к.п'], match_pos=MatchPosition.RIGHT),
    Definition(value="кишлак", abbreviations=[]),
    Definition(value="поселковый совет", abbreviations=['пс', 'поссовет'], match_pos=MatchPosition.RIGHT),
    Definition(value="дачный поселковый совет", abbreviations=['д.п'], match_pos=MatchPosition.RIGHT),
    Definition(value="волость", abbreviations=['вл', 'в.л'], match_pos=MatchPosition.LEFT),
    Definition(value="сельский совет", abbreviations=['сс', 'сельсовет'], match_pos=MatchPosition.RIGHT),
    Definition(value="сомон", abbreviations=['смн']),
    Definition(value="населённый пункт", abbreviations=['н.п', 'нп'], match_pos=MatchPosition.RIGHT),
    Definition(value="посёлок сельского типа", abbreviations=['п'], match_pos=MatchPosition.RIGHT),
    Definition(value="посёлок при станции", abbreviations=['п.ст'], match_pos=MatchPosition.RIGHT),
    Definition(value="железнодорожная станция", abbreviations=['ж.д ст'], match_pos=MatchPosition.RIGHT),
    Definition(value="село", abbreviations=['село'], match_pos=MatchPosition.RIGHT),
    Definition(value="деревня", abbreviations=['д'], match_pos=MatchPosition.RIGHT),
    Definition(value="местечко", abbreviations=['м']),
    Definition(value="слобода", abbreviations=['сл'], match_pos=MatchPosition.LEFT),
    Definition(value="станица", abbreviations=['ст-ца'], match_pos=MatchPosition.RIGHT),
    Definition(value="хутор", abbreviations=['х'], match_pos=MatchPosition.RIGHT),
    Definition(value="улус", abbreviations=['у'], match_pos=MatchPosition.RIGHT),
    Definition(value="разъезд", abbreviations=['рзд'], match_pos=MatchPosition.RIGHT),
    Definition(value="зимовье", abbreviations=['зим'], match_pos=MatchPosition.LEFT),
    Definition(value="совхоз", abbreviations=['свх'], match_pos=MatchPosition.RIGHT),
    Definition(value="колхоз", abbreviations=['клх'], match_pos=MatchPosition.RIGHT),
]

STREET_DEFINITIONS = [
    Definition(value="бульвар", abbreviations=['бул, б-р']),
    Definition(value="вал", abbreviations=[]),
    Definition(value="вывоз", abbreviations=[]),
    Definition(value="въезд", abbreviations=[]),
    Definition(value="дорога", abbreviations=['дор']),
    Definition(value="заезд", abbreviations=[]),
    Definition(value="линия", abbreviations=[]),
    Definition(value="кольцо", abbreviations=[]),
    Definition(value="луч", abbreviations=[]),
    Definition(value="площадь", abbreviations=['пл']),
    Definition(value="проезд", abbreviations=['пр, пр-д']),
    Definition(value="разъезд", abbreviations=[]),
    Definition(value="спуск", abbreviations=[]),
    Definition(value="перспектива", abbreviations=[]),
    Definition(value="проулок", abbreviations=[]),
    Definition(value="съезд", abbreviations=[]),
    Definition(value="проспект", abbreviations=['просп, пр-кт']),
    Definition(value="территория", abbreviations=[]),
    Definition(value="тракт", abbreviations=[]),
    Definition(value="тупик", abbreviations=['туп']),
    Definition(value="улица", abbreviations=['ул.']),
    Definition(value="шоссе", abbreviations=['ш']),
    Definition(value="аллея", abbreviations=['ал']),
    Definition(value="магистраль", abbreviations=['маг']),
    Definition(value="набережная", abbreviations=['наб']),
    Definition(value="переулок", abbreviations=['пер']),
]